// guess the random number.

let number = Math.floor(Math.random()*10) +1;

let guess = -1;

while(guess!==number){
    guess = Number(prompt("enter a number to check if it matches with the random number generated by the computer or not (1 - 10) : "));
    if(isNaN(guess) || guess<1 || guess>10){
        console.log("invalid input. try again!")
        continue;
    }
    if(guess>number){
        console.log("your is to high.");
        break
    }else if(guess<number){
        console.log("your guess is to low.");
        break
    }else{
        console.log("you guessed it correct. the number is : ", number);
    }
}
